Acceptance testing
artross/qna pull request #2
Opened 2016-11-17 17:48 UTC by artross

2016-11-18 11:35 UTC, palkan requested changes
Нужны еще acceptance тесты на создание невалидного ответа/вопроса (пользователь должен видеть ошибки);

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
>    def index
У нас вообще нет индекса для ответов

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
> +  # answers#new doesn't exist anymore
Не надо оставлять закомментированный код.

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.author_id = current_user.id  # <- dunno how to do it better...
Просто `@answer.author = current_user`.

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question) # redirect anyway
А как ты покажешь пользователю ошибки, если ответ не создан?

В случае ошибки должен быть рендер формы с сообщениями, а случае успеха редирект с flash-сообщением об успешном создании.

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.author == current_user
Для сравнения нам достаточно id, а сейчас у тебя только для сравнения подгружается из базы автор запроса.

2016-11-18 11:35 UTC, palkan commented on app/controllers/questions_controller.rb
>      @question.persisted? ? (redirect_to @question) : (render :new)
Нужны сообщения. Пользователь всегда должен видеть реакцию приложения на свои действия.

2016-11-18 11:35 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.author == current_user
Это везде нужно поправить.

2016-11-18 11:35 UTC, palkan commented on app/models/question.rb
> +  belongs_to :author, class_name: "User"
А назвал бы ассоциацию `:user` и не пришлось бы везде дополнительные опции указывать.

2016-11-18 11:35 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Нужен тест, который проверят, что не-автор не может удалить ответ.

2016-11-18 11:35 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).question).to eq(question)
Так ты не проверяешь, что ответ _сохранился_ с правильным вопросом. `assigns(:answer)` – это просто руби-объект.

Через `change` будет так:

```ruby
expect { ... }.to change(question.answers, :count).by(1)
```

Такой же тест нужен и на связь с пользователем.

2016-11-18 11:35 UTC, palkan commented on spec/features/guest/guest_spec.rb
> +feature "Guest functionality", %{
Группировать сценарии нужно исходя из функционала, а не ролей.
Сценарий – это, например, "Создание вопроса", "Создание ответа" и т.п. А уже внутри различные контексты для авторизованного и неавторизованного пользователя.

Удобно группировать по страницам или объектам сценария, например: `"answers/create_answer_spec.rb"`, `"questions/questions_list_spec.rb"`, `"system/log_in_spec.rb"`.

2016-11-18 11:35 UTC, palkan commented on spec/features/guest/guest_spec.rb
> +  given!(:questions) { create_list(:question, 2) }
Можно `create_pair(:question)`

2016-11-18 20:59 UTC, artross commented on app/controllers/answers_controller.rb
> +    @answer.author_id = current_user.id  # <- dunno how to do it better...
Я имел ввиду не знаю как сделать в одну строчку, с использованием `create`

2016-11-18 20:59 UTC, artross commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question) # redirect anyway
`flash-сообщения` это что?

2016-11-18 21:01 UTC, artross commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.author == current_user
А как понять в каком случае рельсы автоматически "сообразят" что нужно использовать `id` (это было в скринкасте, по-моему в предыдущем), а когда нет?

2016-11-18 21:02 UTC, artross commented on app/models/question.rb
> +  belongs_to :author, class_name: "User"
Намеренно :) Зато узнал некоторые нюансы работы с кастомнымно именованными полями

2016-11-18 21:04 UTC, artross commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Он есть как фича. Нужно и в спеке контроллера это продублировать?

2016-11-19 07:56 UTC, artross commented on spec/features/guest/guest_spec.rb
> +  given!(:questions) { create_list(:question, 2) }
Ок, буду знать. В пользу `create_list` можно сказать что поменяв один символ можно быстро сделать не 2 а 3, в случае `create_pair` придется заменить метод.

2016-11-19 08:20 UTC, artross commented on spec/features/guest/guest_spec.rb
> +feature "Guest functionality", %{
Сделано (коммент для меня, чтобы удобнее ориентироваться)

2016-11-19 08:21 UTC, artross commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).question).to eq(question)
Сделано

2016-11-19 11:49 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.author_id = current_user.id  # <- dunno how to do it better...
Например, так:

```Ruby
@question.answers.create(answer_params.merge(author: current_user))
```

Но текущий вариант мне нравится больше, на мой взгляд, более читабельно. Не всегда нужно стремиться к меньшему количеству строчек.

2016-11-19 11:55 UTC, palkan commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question) # redirect anyway
В контроллере доступен специальный объект, `flash`, в котором мы можем хранить данные для использования в следующем запросе этого полтзователя (потом они автоматически удаляются). Такая "одноразовая" сессия.

Обычно flash используют для хранения сообщений при редиректе (это как раз следующий запрос), например:

```Ruby
flash[:notice] = "Answer has been removed"
redirect_to ...
```

Конечно, нужно для показа сообщения обработать flash в шаблоне.

Вот тут подробнее http://guides.rubyonrails.org/action_controller_overview.html#the-flash

2016-11-19 11:56 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.author == current_user
Когда у тебя есть соответствующая ассоциация. По сути, ты присваиваешь ассоциацию, а рельсы определяют, какой-то нужно ключ прописать.

2016-11-19 11:59 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
В фиче ты просто проверяешь наличие ссылки.
А тут мы проверяем, что если негодяй-пользователь сделает запрос ручками, то у него ничего не получится.

2016-11-19 12:00 UTC, palkan commented on spec/features/guest/guest_spec.rb
> +  given!(:questions) { create_list(:question, 2) }
Ну очень редко бывает нужно больше 2х. В тестах нужно стараться создавать как можно меньше объектов, тем более в базе; это замедляет время прохождения тестов.

2016-11-19 12:12 UTC, artross commented on app/controllers/answers_controller.rb
> +    @answer.author_id = current_user.id  # <- dunno how to do it better...
Вот это то что нужно! Как по мне, читаемость не пострадала. Если бы там было ещё пара вложенных вызовов, тогда конечно да...

2016-11-19 12:12 UTC, artross commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question) # redirect anyway
Спасибо

2016-11-19 12:14 UTC, artross commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.author == current_user
Ага.. то есть это работает только на присваивании, да и то не всегда. Ок, сравнения все поправлю.

2016-11-19 12:32 UTC, artross commented on app/controllers/answers_controller.rb
> +  # answers#new doesn't exist anymore
Сделано

2016-11-19 12:35 UTC, artross commented on app/controllers/answers_controller.rb
>    def index
Сделано

2016-11-19 13:10 UTC, artross commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Сделано

2016-11-19 14:51 UTC, artross commented on app/controllers/questions_controller.rb
>      @question.persisted? ? (redirect_to @question) : (render :new)
Сделано

2016-11-20 10:53 UTC, merged