Ajax 2
artross/qna pull request #4
Opened 2016-12-02 20:55 UTC by artross

2016-12-03 12:04 UTC, palkan requested changes

2016-12-03 12:04 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @current_best_answer = @question.answers.detect { |a| a.best_answer }
Вот это всё нужно, во-первых, вынести в модель (в контроллере не должно быть бизнес-логики), во-вторых, оптимизировать (сбросить предыдущий лучший можно и не находя его).

2016-12-03 12:04 UTC, palkan commented on spec/features/answers/best_answer_spec.rb
> +    # ... and then what? I don't know how to test this.
Например, так:

```ruby
within ".answer:first-child" do
  expect(page).to have_content('Best answer!')
end
```

И аналогичную проверку можно добавить и в сценарии, где ты меняешь лучший ответ, чтобы проверить, что позиция меняется и без перезагрузки страницы.

2016-12-03 12:06 UTC, artross commented on spec/features/answers/best_answer_spec.rb
> +    # ... and then what? I don't know how to test this.
Точно, про псевдо-селекторы забыл...

2016-12-03 12:11 UTC, artross commented on app/controllers/answers_controller.rb
> +    @current_best_answer = @question.answers.detect { |a| a.best_answer }
В модель вынести поиск текущего лучшего ответа это не проблема. Но вот насчёт оптимизации... я так понимаю, предлагается хранить best_answer_id в самом вопросе и тогда будет логично вообще не хранить best_answer в ответе. Но так появится дополнительный гемор с проверками на уровне вопроса, чтобы исключить случаи присваивания айдишника ответа, который к этому вопросу не относится. Точно ли это будет оптимальнее?

2016-12-03 12:50 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @current_best_answer = @question.answers.detect { |a| a.best_answer }
Ни в коем случае не надо хранить ничего в вопросе.
Всё гораздо проще: мы можем _обнулить_ `best_answer` у всех ответов вопроса сразу, нам не нужно для этого искать конкретный.

2016-12-03 14:55 UTC, artross commented on spec/features/answers/best_answer_spec.rb
> +    # ... and then what? I don't know how to test this.
Готово

2016-12-03 14:57 UTC, artross commented on app/controllers/answers_controller.rb
> +    @current_best_answer = @question.answers.detect { |a| a.best_answer }
Я конечно не знаю всех нюансов рельс, но логика подсказывает, что массовое обнуление не будет быстрее. Оно даже будет медленнее, потому что должно будет проверить все ответы, а `detect` остановится на первом (чего нам в данном случае достаточно)

2016-12-04 10:18 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @current_best_answer = @question.answers.detect { |a| a.best_answer }
А тут как раз нет никакой магии. Под массовым обновлением я имею в виду `question.answers,update_all(...)`, а в этом случае будет всего лишь один запрос в базу.

2016-12-04 14:44 UTC, palkan requested changes
И тесты метода `pick_as_best` в модели нужны.

2016-12-04 14:44 UTC, palkan commented on app/models/answer.rb
> +    question.answers.update_all(best_answer: false)
А куда транзакция делась?

2016-12-04 14:52 UTC, artross commented on app/models/answer.rb
> +    question.answers.update_all(best_answer: false)
Так update_all все равно колбеки и валидации игнорирует, не поймёшь успешно он завершился или нет...

2016-12-04 18:49 UTC, palkan commented on app/models/answer.rb
> +      self.update(best_answer: true)
`update!`

2016-12-04 19:40 UTC, artross commented on app/models/answer.rb
> +      self.update(best_answer: true)
Да, упустил этот момент, спасибо ))

2016-12-04 19:42 UTC, merged