Task 8
artross/qna pull request #5
Opened 2017-01-14 22:12 UTC by artross

2017-01-16 10:30 UTC, palkan requested changes

2017-01-16 10:30 UTC, palkan commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Объясни-ка мне, зачем ты это делаешь? Опция `accept_nested_attributes` делает примерно то же самое (только лучше и надежнее), тебе вообще не нужно ничего тут писать.

Просто `@answer = @quetsion.answers.create(answer_params.merge(author: current_user)`.

Тебя самого не смутило такое количество кода в контроллере?

Давай-ка перечитаем [документацию](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) и всё перепишим)

2017-01-17 14:13 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
А фиг знает, не помню уже... возможно это осталось от попыток подружить cocoon и multiple file input-ы. Попробую переделать.

2017-01-17 16:33 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Не прокатывает. Вот такие параметры, такая ошибка: http://prntscr.com/dwtree
Подозреваю что это может быть связано с тем, что в параметрах приходит массив файлов. Хотя в методе answer_params это указано...
params.require(:answer).permit(:body, attachments_attributes: [file: []])

2017-01-17 16:35 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
В документации каких-то особенностей работы с такой структурой вложенных параметров вроде не описано.

2017-01-17 16:39 UTC, palkan commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
У тебя неверный формат параметров, ты пытаешься в одну модель Attachment  запихнуть массив файлов.

Правильный формат:

```ruby
{ "answer" => { "attachment_attributes" => { "0" => { "file" => <ActionDispatch::Http...>}, "1" => { "file" => <ActionDispatch::Http...> }, ... } }
```

И, соответственно, фильтрация:

```ruby
def answer_params
  params.require(:answer).permit(:body, attachment_attributes: [:file])
end
```

2017-01-17 16:49 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Так это сами рельсы такой формат параметров используют. Скорее всего, потому что файловый инпут один. Перехватывать параметры и переформировывать их на нужный лад? Тоже как-то криво. А как иначе можно сделать?

2017-01-17 16:51 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Если просто изменить фильтрацию, то никаких Attachment-ов вообще создано не будет. Создастся только ответ без вложений.

2017-01-17 16:55 UTC, palkan commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Поэтому и придуманы такие глючные монстры как cocoon, чтобы работать _по-рельсовому_.

Если мы отказываемся от их использования, то наиболее простым вариантом сейчас будет _форматирование_ параметров в контроллере:

```ruby
def answer_params
   params.require(:answer).permit(:body).tap do |filtered|
     filtered[:attachment_attributes] = params[:attachment_attributes].fetch(:file, []).map(...) if params[:attachment_attributes]
   end
end
```

2017-01-17 16:58 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Но по сути чем это отличается от имеющегося кода? У тебя переформатирование параметров, у меня их ручная обработка. По сути и то и другое костыли, просто твой код красивше )) Разве не так?

2017-01-17 17:00 UTC, palkan commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Не так.

В моём коде есть только преобразование параметров. Всю работу по сохранению (транзакции, ассоциации) делает рельса.
В итоге в коде сами экшенов вообще ничего менять не надо.

2017-01-17 18:15 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Не совсем так у меня получилось в итоге... так, как ты написал, не будет работать по двум причинам: 
1) если сразу сделать `permit(:body)` а потом `tap`, то `attachments_attributes` уже останутся `unpermitted` навсегда
2) выражение `params[:attachments_attributes]` не имеет смысла, т.к. либо `params[:answer][:attachments_attributes]`, либо например вот так:
`params.require(:answer).tap do |answer|
  answer[:attachments_attributes] = answer[:attachments_attributes].each_with_object({}) do |(k,v), obj|
    v.fetch(:file, []).each { |e| obj[obj.keys.count.to_s] = { file: e } }
  end if answer[:attachments_attributes]
end.permit(:body, attachments_attributes: [:file])`
Есть замечания?

2017-01-17 18:16 UTC, artross commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Как ты отступы ставил? У меня каша получилась...

2017-01-17 18:41 UTC, palkan commented on app/controllers/answers_controller.rb
> +        if answer_params[:attachments_attributes] &&
Норм

2017-01-17 19:19 UTC, palkan requested changes

2017-01-17 19:19 UTC, palkan commented on app/controllers/answers_controller.rb
> +      rescue
А это тут зачем? Если ты хочешь поймать какую-то конкретную ошибку, то надо указывать её тип, а не ловить всё подряд.
Во-вторых, используй `update` и обрабатывай значение.

2017-01-17 19:19 UTC, palkan commented on app/controllers/attachments_controller.rb
> +      if @attachment.destroy then
`then`?

2017-01-17 19:19 UTC, palkan commented on app/controllers/questions_controller.rb
> +    # this leads to strange "undefined method `email' for nil:NilClass" error
У тебя _пустой_ ответ попадает в список, ты, видимо, пытаешься вывести email автора, вот и ошибка. Надо обрабатывать эту ситуацию. Если тебе вообще нужен этот пустой ответ.

2017-01-17 19:19 UTC, palkan commented on app/controllers/questions_controller.rb
> +        @question.update!(question_params)
Та же ошибка.

2017-01-17 19:19 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Имеет смысл этот код вынести в модуль.

2017-01-17 19:19 UTC, palkan commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content "Answer successfully added"
Надо еще _увидеть_ ссылку на странице

2017-01-17 19:19 UTC, palkan commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content "Answer successfully added"
И что-то не вижу, где само сохранение? Клик на "Save"

2017-01-17 19:19 UTC, palkan commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content "Answer successfully added"
То же самое касается и остальных тестов в этом файле.

2017-01-17 19:20 UTC, artross commented on app/controllers/answers_controller.rb
> +      rescue
Так а что обрабатывать? Я бы с удовольствием... вот при создании есть `persisted?`, а тут?

2017-01-17 19:21 UTC, artross commented on app/controllers/attachments_controller.rb
> +      if @attachment.destroy then
смешение языков в голове ))) что интересно, на работоспособность не влияет

2017-01-17 19:22 UTC, palkan commented on app/controllers/answers_controller.rb
> +      rescue
Как у тебя раньше было?

```ruby
if answer.udpate(...)
  ...
else
 ...
end
```

2017-01-17 19:23 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Имеешь ввиду, что в `question_params` и `answer_params` дублирование кода? В какой модуль лучше вынести, будет ли это rails_helper или что-то другое?

2017-01-17 19:28 UTC, artross commented on spec/features/answers/create_answer_spec.rb
> +      expect(page).to have_content "Answer successfully added"
при создании ответа кнопка submit называется "Add answer", на неё собственно и идёт нажатие. А про какую ссылку речь?

2017-01-17 19:29 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Не, это можно вынести в консерн для контроллеров, назвать это `attachments_params`.

2017-01-17 19:49 UTC, artross commented on app/controllers/questions_controller.rb
> +    # this leads to strange "undefined method `email' for nil:NilClass" error
Пустой ответ наверное был задуман для формы нового ответа, как показано в скринкасте. Теперь понятно в чем суть ошибки была.

2017-01-18 08:37 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
т.е. будет что-то типа такого:
```ruby
# questions_controller
def question_params
  params.require(:question).tap { |q| attachment_params(q) }.permit(:title, :body, attachments_attributes: [:file])
end
```

Наверное можно сделать через `yield`?

2017-01-18 10:47 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Я бы сделал такой интерфейс:

```ruby
def question_params
  params.require(:question).permit(:title, :body).tap do |filtered|
     extract_attachment_params!(params, filtered)
  end
end

def extract_attachment_params(params, target)
   target[:attachment_attributes] = params. ... .permit(attachment_attributes: [:file])
end
```

Сейчас получается, у нас сама обработка в методе, а `permit` на эти атрибуты торчит наружу – никакого разделения ответственности.

2017-01-18 10:56 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
У меня большие сомнения на тему того, что передаётся в `tap` после `permit(:title, :body)`. Я вчера смотрел отладчиком - там всё остальное отсекается, уже никаких `attachments_attributes` не остаётся в результирующем объекте. Может конечно я где-то что-то накосячил, но вроде там особо негде...

2017-01-18 10:59 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Всё верно, там уже ничего нет. Для этого у меня в метода два аргумента: первый – это исходные параметры, а второй – уже отфильтрованные, куда мы хотим добавить наши attachments_attributes.

2017-01-18 11:30 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
ага... то есть мы можем как бы сделать `permit` несколько раз в разных местах, а потом получившееся - склеить... но тогда вот такое сомнение как разрешить: `extract_attachment_params`, как я понял, нужно отправить в консерн, и тогда получится, что один пермит для одной части параметров будет происходить в контроллере, а второй для `attachments`, а также их "склейка" - в консерне. это нормально?

2017-01-18 11:47 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Что значит "в разных местах"? Всё в одном месте – в контроллере; консерн – это не отдельная же сущность, он расширяет контроллер.

2017-01-18 12:05 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Похоже придется третий параметр передавать, по такой схеме. Для того чтобы вытащить `attachments_attributes` из исходных параметров, нужно обратиться сперва по ключу `:question` или `:answer` - таким образом будет
```ruby
# controller
def question_params
  params.require(:question).permit(:title, :body).tap do |filtered|
     extract_attachment_params!(params, filtered, :question)
  end
end

# concern
def extract_attachment_params(params, target, symbol)
   target[:attachment_attributes] = params[symbol][:attachments_attributes]. ... 
end
```

2017-01-18 12:07 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Зачем? Передай сразу `extract_attachment_params!(params[:question], filtered)`

2017-01-18 12:09 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Да, так лучше! :+1: 
И всё же, что ты имел ввиду в комментариях к блоку ниже, про "увидеть ссылку"? Мне кажется там все норм...

2017-01-18 12:18 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Да, там всё норм, не так понял тебя.

2017-01-18 12:49 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
```ruby
def extract_attachments_params!(params, target)
  if params[:attachments_attributes]
    target[:attachments_attributes] = params[:attachments_attributes].each_with_object({}) do |(k,v), obj|
      v.each { |e| obj[obj.keys.count.to_s] = { file: e } }
    end
    target.permit(attachments_attributes: [:file])
  end
end
```

Два момента: 
1) вынес `permit` в отдельный оператор, потому что если цеплять его к результату `each_with_object`, то там просто хэш, рельсы ругаются что у него нет метода `permit`
2) `rspec` пишет что `each_with_object is deprecated and will be removed in rails 5.1` - как посоветуешь исправить, использовать вместо него `reduce`?

2017-01-18 13:09 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
2. `each_wtih_object` не имеет никакого отношения к Rails, это стандартный Ruby метод (http://ruby-doc.org/core-2.4.0/Enumerable.html#method-i-each_with_object).

В `attachments_attributes` лучше поместить массив, а не хэш (рельсы поймут):

```ruby
target[:attachments_attributes] = params[:attachment_attributes].map { |p| p[:file] }.flat_map { |f| { file: f } }
```

И никакой `permit` вообще не нужен.

2017-01-18 13:28 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Ну вот пишет `rspec` такое... что с этим делать, забить?

2017-01-18 13:38 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Полный вывод мне покажи

2017-01-18 13:40 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
http://prntscr.com/dx74e0

2017-01-18 13:51 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Ох, да уж, намудрили они с параметрами.

Тогда придётся сначала фильтровать, потом брать обычный хэш и с ним работать:

```ruby
params.permit(attachment_attributes: [:file]).to_h.fetch(:attachment_attributes, []).map { |p| p[:file] }.flat_map { |f| { file: f } }
```

2017-01-18 14:09 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Так мы же с этого начали, что не можем фильтровать таким образом, потому что по ключу `:file` лежит массив. Если сделать `params.permit(attachments_attributes: [:file])` то сразу же весь массив файлов будет отсечён и по ключу `:attachments_attributes` останется пусто http://prntscr.com/dx7irz

2017-01-18 14:12 UTC, palkan commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
А как отфильтровать массив? На сколько я помню, вот так: `params.permit(attachments_attributes: [file: []])`.

2017-01-18 14:14 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Да, у меня так было для фильтрации параметров перед ручной обработкой. Я в начале обсуждения так понял, что не стоило делать подобную фильтрацию. Ну если без этого никак то сделаю.

2017-01-18 14:57 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
Еще пара нюансов, если я правильно понял твою мысль:
1) вместо `.map { |p| p[:file] }` нужно сделать `.map { |k,v| v[:file] }` иначе просто ошибка приведения символа к числу
2) вместо `flat_map` нужно `flatten.map`, потому что на входе массив, единственным элементом которого является тоже массив, а `flat_map` грубо говоря сперва делает `map` а потом уже плющит результат.

2017-01-18 15:03 UTC, artross commented on app/controllers/questions_controller.rb
> +      question[:attachments_attributes] = question[:attachments_attributes].each_with_object({}) do |(k,v), obj|
В общем, надо ехать... кидаю всё в Teachbase, спасибо за продуктивный день и ценные советы!

2017-01-18 18:27 UTC, palkan approved these changes

2017-01-21 20:21 UTC, merged