Task 9
artross/qna pull request #6
Opened 2017-01-25 15:27 UTC by artross

2017-01-26 07:19 UTC, palkan requested changes

2017-01-26 07:19 UTC, palkan commented on app/controllers/votes_controller.rb
> +      respond_to do |format|
Зачем тебе `respond_to`? Ты работаешь с одним форматом, можно всегда отдавать json.

2017-01-26 07:19 UTC, palkan commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Идея кэшировать рейтинг хорошая, но реализация не такая простая, как можно подумать.
Такое решение очень быстро сломается в реальной жизни, когда несколько запросов на создание голоса будет одновременно. Итоговый рейтинг будет неверный, потому что с момента, когда ты загрузил votable, его рейтинг уже мог изменится в другом запросе.

Я предлагаю пока отложить кэширование рейтинга, а просто добавить метод рейтинг в votable:

```ruby
def rating
  votes.sum(:value)
end
```

Вернемся лучше к этому вопросу после завершения курса, а то можем не успеть.

2017-01-26 07:19 UTC, palkan commented on app/controllers/votes_controller.rb
> +      Vote.transaction do
Ну и снова: в контроллере не должно быть много логики.
Задача контроллера – получить данные от пользователя и передать их _ниже_ (в модель, сервис, и т.п.).
В _хорошем_ методе контроллера должно быть всего строчек 5 кода. Если видишь, что их сильно больше – повод задуматься о том, а в правильном ли месте реализован функционал.

2017-01-26 07:19 UTC, palkan commented on app/helpers/votes_helper.rb
> +module VotesHelper
Удаляем пустой хэлпер.

2017-01-26 07:19 UTC, palkan commented on app/models/concerns/votable.rb
> +    vote = find_vote(user)
`find_vote(user)&.value || 0`

2017-01-26 07:19 UTC, palkan commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self, author: user).take
`votes.find_by(author: user)`

2017-01-26 07:19 UTC, palkan commented on spec/helpers/votes_helper_spec.rb
> +require 'rails_helper'
И это удалить

2017-01-26 18:58 UTC, artross commented on app/controllers/votes_controller.rb
> +      Vote.transaction do
Т.е. транзакции тоже должны быть в моделях?

2017-01-26 19:08 UTC, artross commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Оно не так чтобы "сломается", оно может отставать по актуальности. Но это и в предложенном тобой варианте тоже будет происходить: пока мы тут сидим изучаем ответы, за них уже проголосовали десять новых человек - а мы этого не видим. Тут, насколько я понимаю, для создания иллюзии актуальности рейтингов нужно при загрузке страницы подключать событие, которое будет через каждый небольшой промежуток времени опрашивать сервер на предмет этих самых актуальных значений...

А сама по себе ситуация нескольких одновременных запросов вызовет дэдлок на таблице вопросов/ответов, который обрубит лишние запросы и не изменит рейтинг у части пользователей. Ну и собственно ничего страшного, они могут нажать на кнопку еще несколько раз, как это частенько и происходит )))) Опять же, не знаю точно, какой уровень изоляции транзакций выставляют рельсы при взаимодействии с тем же постгресом, я и rails и pg использовал только в учебных проектах... если блокировка выставляется по набору фильтрованных записей - то да, твой вариант не вызовет дэдлоков, в этом смысле он лучше.

Резюме: переделывать или нет? :)

2017-01-26 19:10 UTC, artross commented on app/controllers/votes_controller.rb
> +      respond_to do |format|
Не знаю, сделал как в скринкасте, не углублялся в такие нюансы как "что такое respond_to"...

2017-01-26 19:11 UTC, artross commented on app/models/concerns/votable.rb
> +    vote = find_vote(user)
Поясни плиз, вот эту конструкцию `&.` впервые вижу

2017-01-26 19:12 UTC, artross commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self, author: user).take
т.е. в данном случае `votes` это `self.votes`?

2017-01-26 19:12 UTC, palkan commented on app/controllers/votes_controller.rb
> +      Vote.transaction do
Именно

2017-01-26 19:14 UTC, palkan commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Оно не будет отставать, оно собьется и не вернется к _актуальному_ значению.
А вариант предложенный мной будет актуальным.

Вот посмотри, например, https://vladmihalcea.com/2014/09/14/a-beginners-guide-to-database-locking-and-the-lost-update-phenomena/.

2017-01-26 19:14 UTC, palkan commented on app/models/concerns/votable.rb
> +    vote = find_vote(user)
http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

2017-01-26 19:31 UTC, artross commented on app/models/concerns/votable.rb
> +    vote = find_vote(user)
done (как обычно, это коммент для меня)

2017-01-26 19:31 UTC, artross commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self, author: user).take
done

2017-01-26 19:32 UTC, artross commented on spec/helpers/votes_helper_spec.rb
> +require 'rails_helper'
done

2017-01-26 19:33 UTC, artross commented on app/helpers/votes_helper.rb
> +module VotesHelper
done

2017-01-26 19:34 UTC, artross commented on app/controllers/votes_controller.rb
> +      respond_to do |format|
done

2017-01-26 20:01 UTC, artross commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Ну тут просто я "смалодушничал" ))) Видел в какой-то статье рекомендацию выполнять в транзакции как можно меньше расчётов (как выяснилось, рекомендация применима крайне редко когда). Тут нужно перенести строку, вычисляющую `new_rating`, внутрь транзакции, и тогда конкурентная транзакция для вычисления своего нового рейтинга будет вынуждена подождать коммита.

2017-01-26 20:06 UTC, artross commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Я сделаю в итоге твой вариант, потому что дэдлоки это всё-таки зло, а ты напиши плиз если в моем комменте выше есть ошибка в логике.

2017-01-26 20:28 UTC, artross commented on app/controllers/votes_controller.rb
> +      Vote.transaction do
done (транзакции испарились)

2017-01-26 20:35 UTC, artross commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
Запушил всё и кинул ссылку в teachbase. Ещё вот какой момент, ты пишешь в первом сообщении: "Вернемся лучше к этому вопросу после завершения курса, а то можем не успеть."

В связи с чем резонный вопрос: а можем успеть? :) Нет, я конечно был бы только за, но курс заканчивается через 4 недели, а у меня доделывается 9-я задача и 23-х, при том что первые две и задачами-то не были... Конечно на прошлой задаче было потеряно полтора месяца по ряду неудачно сложившихся причин, но всё равно, программа курса кажется несоответствующей срокам ))) Даже вон Женя Морозов из группы Виталия не успеет судя по всему. Сколько человек успеют со всего потока, один наверное? Не удивлюсь если он уже пару лет как рельсовый разраб и пришёл поучиться нюансам и тонкостям у таких профи как вы :)

2017-01-27 07:19 UTC, palkan commented on app/controllers/votes_controller.rb
> +        @votable.update!(rating: new_rating)
По поводу транзакции.
Просто перенести внутрь - не поможет.
Проблема не в обновлении, а в загрузке начальной версии votable, в которой старый рейтинг.
Помимо транзакции тут нужна ещё и блокировка это записи (иначе для чтения она будет доступна из других транзакций по-прежнему).

По поводу курса.
Пока ещё можно успеть, дальше сами задания будут попроще (может, кроме парочки).
В любом случае, будет возможность продлить (платно или бесплатно, в зависимости от прогресса). 
Виталий расскажет ближе к концу.

2017-01-29 15:16 UTC, merged